### ISSUE TITLE
How to run advanced demo

### ISSUE THREAD

**Issue by libojacky** [pierrre/imageserver#14]
when i use advanced demo to run is ok,
but browse the url like localhost:8080/image/1.jpg
the result is :  invalid param "path": unknown image "image/1.jpg"
so,please tell me how to use advanced demo 
if i want to use graphicsmagick,how to use
thank you!

**Comment by pierrre** [comment]
> the result is : invalid param "path": unknown image "image/1.jpg"

Yes, the `advanced` example only allows to use images from the `testdata` directory.
See https://imageserver.pierredurand.fr/large.jpg?width=200

> if i want to use graphicsmagick,how to use

I strongly discourage you to use it.
It was an early experiment, and I personally don't use it anymore.
If you really want to use it, use the `Handler` from https://github.com/pierrre/imageserver/blob/master/graphicsmagick/graphicsmagick.go
