### ISSUE TITLE
Help deploying to App Engine

### ISSUE THREAD

**Issue by saeho** [pierrre/imageserver#15]
Hi Pierrre,

I would like some help deploying a golang image server using your package to the Google App Engine.

Problem is, App Engine rejects the use of sockets. I think in order to rectify the issue, "google.golang.org/appengine/socket" package is necessary.

I'm trying to follow this github issue to fix the issue: https://github.com/go-sql-driver/mysql/issues/457

```
"google.golang.org/appengine"
"github.com/go-sql-driver/mysql"
"google.golang.org/appengine/socket"

dial := func(addr string) (net.Conn, error) {
        return socket.Dial(appengine.NewContext(r), "tcp", addr)
    }

mysql.RegisterDial("external", dial)
```

However, I'm not sure how I could get access to the http request from where the Redis socket.Dial() is called.

**Comment by pierrre** [comment]
Hi !
Thanks for your interest in my project.

Sadly, I don't know Google App Engine at all.
Which part of the `imageserver` causes issue ?
What is the error ?

May I suggest to use Google Compute Engine instead of Google App Engine ?
I think it lets you deploy ode more "freely".

**Comment by saeho** [comment]
Yes... actually my first original attempt was to use Google Compute Engine. But I couldn't quite figure out how to deploy GoLang apps properly so I resorted to App Engine.

I'll try going back to GCE. You have done a fantastic job with your image server. Thank you.

**Comment by pierrre** [comment]
FYI, my build process is:
- build binaries automatically (I use Travis CI but you can do it manually on your computer)
- upload binaries to a storage (I use AWS S3)
- deploy binaries to server (I pull them with s3cmd)

Go is not installed on my servers.

**Comment by saeho** [comment]
Thank you sir. I didn't realize it was that simple. I was able to deploy it successfully.
