### ISSUE TITLE
Question about the server part.

### ISSUE THREAD

**Issue by edugonch** [pierrre/imageserver#17]
Does it have an stand alone server?

Can I use ssl on a direct configuration or I need to use a proxy like ngnix?

Thank you.

**Comment by pierrre** [comment]
Hello,

imageserver is an image server TOOLKIT.
You can start a Go HTTP server and use it.
See https://github.com/pierrre/imageserver/blob/master/examples/simple/simple.go

**Comment by edugonch** [comment]
I'm sorry, the "server" part un the name confuse me.

Thank you for the answer.
